services:
  api:
    container_name: metasoil_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${DJANGO_PORT}:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    expose:
      - 8000
    command:
      [
        "poetry",
        "run",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000"
      ]
    networks:
      - backend-network
    depends_on:
      - db
      - redis

  celery:
    container_name: metasoil_celery
    build: .
    command: poetry run celery -A api worker -l info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
    networks:
      - backend-network
    depends_on:
      - api
      - redis

  db:
    container_name: metasoil_db
    image: mysql:8.0.20
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysqldbvolume-api:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - backend-network

  redis:
    container_name: metasoil_redis
    image: redis:7.2
    ports:
     - ${REDIS_PORT}:6379
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysqldbvolume-api:
    driver: local
