# Generated by Django 4.2.13 on 2024-07-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'STARTED'), (3, 'SUCCESS'), (4, 'FAILURE'), (5, 'RETRY'), (6, 'REVOKED')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'MEGAHIT'), (2, 'ANNOTATION')]),
        ),
    ]
