# Generated by Django 4.2.13 on 2024-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'Success'), (4, 'Failure'), (5, 'Revoked')], default=1),
        ),
    ]
